### ISSUE TITLE
Hello Friend Can you provide me the sample Alertmanager.yml file 

### ISSUE THREAD

**Issue by mitunmbj** [mr-karan/calert#22]

**Comment by mr-karan** [comment]
```
- name: 'team-myapp'
  webhook_configs:
  - url: 'http://calert:6000/create?room_name=MyAppRoom'
```

There's nothing special, you just need to need to setup like any other `webhook_configs` configuration as described [here](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config).

**Comment by andrewdbate** [comment]
Sorry to be commenting on a closed issue, but I think that it would be good to add this to the README. The `/create` endpoint is documented, but showing a sample config would help.

I was setting up calert, and I was getting an HTTP 400 error in my alertmanager logs. It took me a while to notice that I had forgot to add the query string `?room_name=MyAppRoom` because I only have a single room.

If the example `alertmanager.yml` config snippet you posted above was in the README, I probably would have not made that mistake in my config.

Thanks!

**Comment by mitunmbj** [comment]
Hello Brother, Will Post My both alertmanager.yaml file as well as calert config

alertmanager.yaml
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5m
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'calert'

receivers:
  - name: 'calert'
    webhook_configs:
      - url: http://10.xx.xx.xx:6000/create?room_name=BuyXXXXXXXXAlertsRoom
```
calert (config.toml)

```
# All timeouts and durations are in milliseconds.

[server]
address = ":6000"
socket = "/tmp/calert.sock"
name = "calert"

# WARNING If these timeouts are less than 1s,
# the server connection breaks.
read_timeout=5000
write_timeout=5000
keepalive_timeout=300000

[app]
template_file = "message.tmpl"

[app.http_client]
max_idle_conns =  100
request_timeout = 8000

[app.chat.alertManagerTestRoom]
notification_url = "https://chat.googleapis.com/v1/spaces/xxx/messages?key=abc-xyz&token=token-unique-key%3D"

[app.chat.awesomeRoomTwo]
notification_url = "https://chat.googleapis.com/v1/spaces/xxx/messages?key=abc-xyz&token=token-unique-key%3D"

[app.chat.BuyXXXXXXXXAlertsRoom]
notification_url = "https://chat.googleapis.com/v1/spaces/AAAARelxxx/messages?key=AIzXXXXXXXXXXXXXXXXXXXXXXXX"
```
Here in the config.toml file add a new section "[app.chat.<YourChatroom>" and in the notification_url add you your chat room webhook url
