### ISSUE TITLE
no provider available for room

### ISSUE THREAD

**Issue by ybucci** [mr-karan/calert#75]
Error LOG
```
(*Notifier).Dispatch","file":"/home/runner/work/calert/calert/internal/notifier/notifier.go","line":41},"msg":"dispatching alerts","count":1}
{"time":"2024-03-26T17:01:19.101881613Z","level":"ERROR","source":{"function":"github.com/mr-karan/calert/internal/notifier.(*Notifier).Dispatch","file":"/home/runner/work/calert/calert/internal/notifier/notifier.go","line":45},"msg":"no provider available for room","room":"cattle-monitoring-system/alertas/alertas"}
{"time":"2024-03-26T17:01:19.102244707Z","level":"ERROR","source":{"function":"main.handleDispatchNotif.func1","file":"/home/runner/work/calert/calert/cmd/handlers.go","line":109},"msg":"error dispatching alerts","error":"no provider configured for room: cattle-monitoring-system/alertas/alertas"}
```

AlertManager Config

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertas
  namespace: cattle-monitoring-system
spec:
  receivers:
    - name: alertas
      webhookConfigs:
        - url: http://caalert-calert:6000/dispatch
  route:
    groupBy:
      - job
    groupInterval: 5m
    groupWait: 30s
    receiver: alertas
    repeatInterval: 12h
```

ConfigMap
```
   [providers.alertas]
  
    type = "google_chat"
  
    endpoint =
    "https://chat.googleapis.com/v1/spaces/XXXXXXXXXXXXXXXXXXXXXXXXX"
  
    max_idle_conns = 50
  
    timeout = "30s"
  
    proxy_url = ""
  
    template = "static/message.tmpl"
  
    thread_ttl = "12h"
  
    dry_run = "false"
```

**Comment by NotLGBT** [comment]
Your "calert" name is must be corresponding to your provider in this case "calert". So like that
`**calert:**
  #   type: "google_chat" # Type of provider. Currently supported value is `google_chat`.
  #   endpoint: "https://chat.googleapis.com/v1/spaces Webhook URL
  #   max_idle_conns:  50 # Max idle connections in the HTTP Client.
  #   timeout: "30s" # Timeout for making requests to Provider.
  #   template: "static/message.tmpl" # Path to specify the message template path.
  #   thread_ttl: "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
  #   dry_run: false`  
` - name: 'prod_alerts'
      webhook_configs:
      - url: 'http://**calert**:6000/dispatch'
`

**Comment by Ancocodet** [comment]
The Problem is that in Kubernetes (which your configuration looks like) the rooms/receivers are always prefixed with the namespace and the name of config (namespace/config_name/receiver).
You cab use the query parameter **room_name** with the dispatch endpoint and set it to the receiver name, that should fix the error.

For example:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertas
  namespace: cattle-monitoring-system
spec:
  receivers:
    - name: alertas
      webhookConfigs:
        - url: http://caalert-calert:6000/dispatch?room_name=alertas
  route:
    groupBy:
      - job
    groupInterval: 5m
    groupWait: 30s
    receiver: alertas
    repeatInterval: 12h
```
