### ISSUE TITLE
Alert template error

### ISSUE THREAD

**Issue by NYARAS** [mr-karan/calert#78]
Alert templating `*({{.Labels.severity | toUpper }})`  fails when you don't have `severity` in alert rules into a string.

Example:

```yaml
        - alert: High Node CPU Usage
          annotations:
            summary: Example summary
          expr: |
            <Example Expr>
          for: 5m
          labels:
            team: devops
            severity: "critical"
```
This will pass but

```yaml
        - alert: High Node CPU Usage
          annotations:
            summary: Example summary
          expr: |
            <Example Expr>
          for: 5m
          labels:
            team: devops
            severity: critical # without quotes
```

This fails with `msg="Error parsing values in template" error="template: message.tmpl:1:23: executing \"message.tmpl\" at <toUpper>: invalid value; expected string"`
