### ISSUE TITLE
Cannot choose a custom template name in "template: "static/xxx.tmpl"

### ISSUE THREAD

**Issue by diegocejasprieto** [mr-karan/calert#82]
I'm trying to send notifications using Calert (as a dependency of the Helm chart "kube-prometheus-stack"), AlertManager and a custom tmpl

This is my Calert's values.yaml 
```
calert:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 48Mi
    requests:
      cpu: 5m
      memory: 24Mi

  providers: 

    calert:
      endpoint: "XXXXXXXXXXXXXXXXX"
      template: "static/staging-alert.tmpl"
      dry_run: false 

  templates: 
    staging-alert.tmpl: |
      *({{.Labels.severity | toUpper }}) {{ .Labels.alertname | Title }} - {{.Status | Title }}*
      {{ range .Annotations.SortedPairs -}}
      {{ .Name | Title }}: {{ .Value}}
      {{ end -}}
```

The pod is launched with the '--config=/app/static/config.toml' argument, and if I take a look at that path inside the pod I find the following config:

```
# All timeouts and durations are in milliseconds.

[app]
address = "0.0.0.0:6000"
server_timeout = "60s"
enable_request_logs = "true"
log = "info"
[providers.calert]
type = "google_chat"
endpoint = "XXXXXXXXXXXXXXXXXXX"
max_idle_conns = 50
timeout = "30s"
proxy_url = ""
template = "static/staging-alert.tmpl"
thread_ttl = "12h"
dry_run = "false"
```

However, the Calert's pod logs say this:

```
time="2024-09-30T20:13:04Z" level=info msg="dispatching new alert" receiver=calert
time="2024-09-30T20:13:04Z" level=info msg="dispatching alerts" count=1
time="2024-09-30T20:13:04Z" level=info msg="dispatching alerts to google chat" count=1
time="2024-09-30T20:13:04Z" level=error msg="Error parsing values in template" error="template: message.tmpl: \"message.tmpl\" is an incomplete or empty template"
```

I'm gonna need to have different providers with separate templates files in the future but I cannot even change the template file name for the first provider.
Why the pod is looking for a "message.tmpl" when I stated that the template file should be staging-alert.tmpl in values.yaml?

I'm using this chart in Helm:

- name: "calert"
  repository: "https://mr-karan.github.io/calert/charts"
  version: "v2.1.1"

The Calert's pod picks up the "ghcr.io/mr-karan/calert:v2.0.2" image.
